### QUIZ 2

## 1

In [1]:
# answer with regular parenthesis

## 2

Q 2
Question 2
Suppose that we have defined the following dictionary:

people = {'hugh':49,'kate':35,'lucy':24,'bob':36}

In the following list, three of the code snippets will correctly sum the values in this dictionary. Please select the one snippet that is NOT correct.

a. total = 0
for key in people:
     total += key
b. total = 0
for x in people.values():
     total += x
c. total = sum(people.values())
d. total = 0
for key in people:
     total += people[key]

In [14]:
people = {'hugh':49,'kate':35,'lucy':24,'bob':36}
people

{'hugh': 49, 'kate': 35, 'lucy': 24, 'bob': 36}

In [11]:
# Option 1
total = 0
for key in people:
     total += key

TypeError: unsupported operand type(s) for +=: 'int' and 'str'

In [7]:
total = 0
for x in people.values():
     total += x
        
total

144

In [8]:
total = sum(people.values())
total

144

In [12]:
total = 0
for key in people:
     total += people[key]
        
total

144

Answer: A

## 3

In [13]:
people['dan']

KeyError: 'dan'

Answer: Since 'dan' is not a key, it will raise a 'keyError'

## 4

Q 4
Question 4
Suppose that we have the following list of dictionaries and associated loop of code:

peoplelist = [{'name':'bob','age':28},{'name':'dylan','age':43},{'name':'cat','age':17}]
     for item in peoplelist:
     if item['age']>30:
          print(item['name'])


What will be the result if we execute this code?

In [20]:
peoplelist = [{'name':'bob','age':28},{'name':'dylan','age':43},{'name':'cat','age':17}]
for item in peoplelist:
 if item['age']>30:
        print(item['name'])

dylan


Answer: A

## 5

Q 5
Question 5
Suppose that we define the following mystery function:

def mystery(x):
     if x > 0:
          return −x
     else:
          return x


Which of the following is NOT a true statement?

In [22]:
def mystery(x):
     if x > 0:
          return -x
     else:
          return x

In [26]:
mystery(0)

0

In [27]:
mystery(5)

-5

In [28]:
mystery(-5)

-5

In [29]:
mystery(0)

0

Answer: A (a. Calling mystery(0) returns −5.)

## 6

Q 6
Question 6
Suppose that we define a NumPy array from a list of lists: [Please note that the print statement leaves out commas between elements in the array below.]

import numpy as np
c = np.array([[2,4,6,8],[12,14,16,18],[22,24,26,28]])
print(c)
[[2,4,6,8]
[12,14,16,18]
[22,24,26,28]]


What is the shape of this array as defined by c.shape?

In [30]:
import numpy as np
c = np.array([[2,4,6,8],[12,14,16,18],[22,24,26,28]])
print(c)

[[ 2  4  6  8]
 [12 14 16 18]
 [22 24 26 28]]


In [31]:
c.shape

(3, 4)

Answer: a. (3,4)

## 7

Q 7
Question 7
If we have the same NumPy array c as defined in the previous question, how would we index the array using slices to get the second row [12,14,16,18]?

In [32]:
c[:,1]

array([ 4, 14, 24])

In [33]:
c[1,:]

array([12, 14, 16, 18])

In [34]:
c[2,:]

array([22, 24, 26, 28])

In [36]:
c[:,2]

array([ 6, 16, 26])

Answer: B (b. c[1,:])

## 8

Q 8
Question 8
Suppose that we define a NumPy array:

d = np.array([6,16,26])

How would you use a Boolean mask to assign all the values greater than 10 to be the value 0?

In [58]:
d = np.array([6,16,26])
d

array([ 6, 16, 26])

In [53]:
d = 0
d

0

In [55]:
d[d<=10]=0
d

array([ 0, 16, 26])

In [59]:
d[d>10]=0
d

array([6, 0, 0])

In [57]:
d[d>10]=d
d

ValueError: NumPy boolean array indexing assignment cannot assign 3 input values to the 0 output values where the mask is true

Answer: C (d[d>10]=0)

## 9

Q 9
Question 9
Suppose that we use the datetime package to create two datetime objects:

D1 = datetime(2017,2,22,9,30)
D2 = datetime(2017,2,23,10,45)


Which of the following are operations that you can do with the datetime objects?

In [70]:
import datetime

d1 = datetime.datetime(2017,2,22,9,30)
print(D1)
d2 = datetime.datetime(2017,2,23,10,45)
print(D2)

2017-02-22 09:30:00
2017-02-23 10:45:00


In [71]:
d1 < d2

True

In [73]:
d1 - d2

datetime.timedelta(days=-2, seconds=81900)

In [75]:
d1.strftime("%Y")

'2017'

Answer: d (All of the above)

## 10

Q 10
Question 10
Suppose that you have dictionaries with word frequencies. Each dictionary has strings for the keys and numbers for the values (representing the frequencies of the words in the strings). Here is an example dictionary:

word_freq = {'the':58,'people':6,'beautiful':8,'cats':13}

Write a function that takes as parameters a word frequency dictionary and a threshold number that is an integer. This function should return a result that is a list of all the words whose frequency is greater than the threshold.

For example, suppose that you name your function top_words. If you call the function with the above dictionary and the threshold of 10:

top_words(word_freq, 10)

you should get the result
['the', 'cats'],
where the words can occur in any order.

Please submit the code for this function and the output using the word frequency dictionary listed below. Please show the output of your code using three separate threshold numbers:

word_freq = {'the':58, 'people':6, 'beautiful':8, 'cats':13, 'finally':9, 'this': 19, 'class': 21, 'is': 101, 'almost': 1, 'over':4}

In [77]:
word_freq = {'the':58, 
             'people':6, 
             'beautiful':8, 
             'cats':13, 
             'finally':9, 
             'this': 19, 
             'class': 21, 
             'is': 101, 
             'almost': 1, 
             'over':4}

word_freq

{'the': 58,
 'people': 6,
 'beautiful': 8,
 'cats': 13,
 'finally': 9,
 'this': 19,
 'class': 21,
 'is': 101,
 'almost': 1,
 'over': 4}

In [94]:
def greaterthany(x, y):
    listgreaterthany = []
    for k, v in word_freq.items():
        if int(v) > int(y):
            listgreaterthany.append(k)
    return listgreaterthany
            

In [98]:
greaterthany(word_freq, 11)

['the', 'cats', 'this', 'class', 'is']

In [99]:
greaterthany(word_freq, 15)

['the', 'this', 'class', 'is']

In [100]:
greaterthany(word_freq, 20)

['the', 'class', 'is']

## 11

Q 11
Question 11
For this question, you are to write a program that reads the data in the file EUR.pop.rev.csv. For each line in this file there is a country and seven population numbers between 1989 and 1995.

Choose one of the following to accomplish:

a. Read the data using the csv reader and represent one or more columns of the data in a NumPy array as in read_gasoline_numeric.py.
b. Read the data into a pandas DataFrame using read_csv function.

Your program must also accomplish all of the following:

1. Replace missing data with 0
2. Print each country that has more than 1,000,000 people in 1995
3. Print the average population in the United Kingdom over those seven years

Submit your code along with the output of your program.

You can use code from the class as a template, but it is essential to use appropriate variable names throughout and that you write original comments for what your program does.

In [235]:
# Import needed packages

import pandas as pd
import numpy as np

In [236]:
# Choose pandas dataframe as the data read-in option (versus the numpy option)

dataa = pd.read_csv('/Users/pergolicious/Downloads/eur.pop.rev.csv')
dataa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 8 columns):
 #   Column                           Non-Null Count  Dtype 
---  ------                           --------------  ----- 
 0   European Population (1989-1995)  19 non-null     object
 1   Unnamed: 1                       19 non-null     object
 2   Unnamed: 2                       17 non-null     object
 3   Unnamed: 3                       19 non-null     object
 4   Unnamed: 4                       19 non-null     object
 5   Unnamed: 5                       19 non-null     object
 6   Unnamed: 6                       19 non-null     object
 7   Unnamed: 7                       19 non-null     object
dtypes: object(8)
memory usage: 1.6+ KB


In [237]:
dataa

European Population (1989-1995) Unnamed: 1 Unnamed: 2 Unnamed: 3  \
0                                    NaN        NaN        NaN        NaN   
1                                    NaN   01.01.89   01.01.90   01.01.91   
2                                Austria    7602431    7660345    7790957   
3                                Belgium    9927600    9947800    9987000   
4                                Denmark    5129800    5135400    5146500   
5                                Finland    4954359    4974383    4998478   
6                                 France   56269800        NaN   56893000   
7                                Germany   61715000   62678000   79753000   
8                                Iceland     253500     255708     259577   
9                                Ireland    3526600    3505500    3519000   
10                                 Italy   57504700   57576400   57746200   
11                             Luxemburg     374900     379300     384400   
12                            Netherland   14805240   14892574   15010445   
13                                Norway    4226901    4241473    4261930   
14                              Portugal   10304700        NaN    9858500   
15                                 Spain   38851900   38924500   38993800   
16                                Sweden    8458890    8527040    8590630   
17                           Switzerland    6619973    6673850    6750693   
18                        United Kingdom   57236200   57410600   57649200   
19                                   NaN        NaN        NaN        NaN   
20                          Total Europe  325665440  326962674  345061045   
21                                   NaN        NaN        NaN        NaN   
22  Sources: Eurostat, national agencies        NaN        NaN        NaN   

   Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7  
0         NaN        NaN        NaN        NaN  
1    01.01.92   01.01.93   01.01.94   01.01.95  
2     7860800    7909575    7943652    8054800  
3    10068319   10100631   10130574   10143047  
4     5162100    5180614    5191000    5251027  
5     5029300    5054982    5098754    5116800  
6    57217500   57529577   57847000   58265400  
7    80238000   81338000   81353000   81845000  
8      262193     264922     266783     267806  
9     3542000    3559985    3570700    3591200  
10   57788200   57114161   57201800   57268578  
11     389800     395200     400000     412800  
12   15129200   15354000   15341553   15492800  
13    4273634    4324577    4348410    4370000  
14    9846000    9987500    9776000    9920800  
15   39055900   39790955   39177400   39241900  
16    8644100    8700000    8749000    8837000  
17    6831900    6871500    7021200    7060400  
18   58888800   58191230   58380000   58684000  
19        NaN        NaN        NaN        NaN  
20  347604719  348887853  348540020  372599752  
21        NaN        NaN        NaN        NaN  
22        NaN        NaN        NaN        NaN

In [238]:
# Rename columns as the dates | keep only particular rows as defined below

dataa.columns = dataa.iloc[1,:]
dataa = dataa.iloc[2:19,:]
dataa

1              NaN  01.01.89  01.01.90  01.01.91  01.01.92  01.01.93  \
2          Austria   7602431   7660345   7790957   7860800   7909575   
3          Belgium   9927600   9947800   9987000  10068319  10100631   
4          Denmark   5129800   5135400   5146500   5162100   5180614   
5          Finland   4954359   4974383   4998478   5029300   5054982   
6           France  56269800       NaN  56893000  57217500  57529577   
7          Germany  61715000  62678000  79753000  80238000  81338000   
8          Iceland    253500    255708    259577    262193    264922   
9          Ireland   3526600   3505500   3519000   3542000   3559985   
10           Italy  57504700  57576400  57746200  57788200  57114161   
11       Luxemburg    374900    379300    384400    389800    395200   
12      Netherland  14805240  14892574  15010445  15129200  15354000   
13          Norway   4226901   4241473   4261930   4273634   4324577   
14        Portugal  10304700       NaN   9858500   9846000   9987500   
15           Spain  38851900  38924500  38993800  39055900  39790955   
16          Sweden   8458890   8527040   8590630   8644100   8700000   
17     Switzerland   6619973   6673850   6750693   6831900   6871500   
18  United Kingdom  57236200  57410600  57649200  58888800  58191230   

1   01.01.94  01.01.95  
2    7943652   8054800  
3   10130574  10143047  
4    5191000   5251027  
5    5098754   5116800  
6   57847000  58265400  
7   81353000  81845000  
8     266783    267806  
9    3570700   3591200  
10  57201800  57268578  
11    400000    412800  
12  15341553  15492800  
13   4348410   4370000  
14   9776000   9920800  
15  39177400  39241900  
16   8749000   8837000  
17   7021200   7060400  
18  58380000  58684000

In [239]:
# Reset the index to be country names

dataa.columns
dataa = dataa.set_index(np.nan)
dataa
#dataa
#dataa

1               01.01.89  01.01.90  01.01.91  01.01.92  01.01.93  01.01.94  \
nan                                                                          
Austria          7602431   7660345   7790957   7860800   7909575   7943652   
Belgium          9927600   9947800   9987000  10068319  10100631  10130574   
Denmark          5129800   5135400   5146500   5162100   5180614   5191000   
Finland          4954359   4974383   4998478   5029300   5054982   5098754   
France          56269800       NaN  56893000  57217500  57529577  57847000   
Germany         61715000  62678000  79753000  80238000  81338000  81353000   
Iceland           253500    255708    259577    262193    264922    266783   
Ireland          3526600   3505500   3519000   3542000   3559985   3570700   
Italy           57504700  57576400  57746200  57788200  57114161  57201800   
Luxemburg         374900    379300    384400    389800    395200    400000   
Netherland      14805240  14892574  15010445  15129200  15354000  15341553   
Norway           4226901   4241473   4261930   4273634   4324577   4348410   
Portugal        10304700       NaN   9858500   9846000   9987500   9776000   
Spain           38851900  38924500  38993800  39055900  39790955  39177400   
Sweden           8458890   8527040   8590630   8644100   8700000   8749000   
Switzerland      6619973   6673850   6750693   6831900   6871500   7021200   
United Kingdom  57236200  57410600  57649200  58888800  58191230  58380000   

1               01.01.95  
nan                       
Austria          8054800  
Belgium         10143047  
Denmark          5251027  
Finland          5116800  
France          58265400  
Germany         81845000  
Iceland           267806  
Ireland          3591200  
Italy           57268578  
Luxemburg         412800  
Netherland      15492800  
Norway           4370000  
Portugal         9920800  
Spain           39241900  
Sweden           8837000  
Switzerland      7060400  
United Kingdom  58684000

In [240]:
# 1. Replace missing data with 0

data = dataa.replace(np.nan, 0)
data = data.apply(pd.to_numeric)
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17 entries, Austria to United Kingdom
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   01.01.89  17 non-null     int64
 1   01.01.90  17 non-null     int64
 2   01.01.91  17 non-null     int64
 3   01.01.92  17 non-null     int64
 4   01.01.93  17 non-null     int64
 5   01.01.94  17 non-null     int64
 6   01.01.95  17 non-null     int64
dtypes: int64(7)
memory usage: 1.1+ KB


In [249]:
# 2. Print each country that has more than 1,000,000 people in 1995

data2 = data[data['01.01.95'] > 1000000]
data2 = data2.iloc[:,6]
print(data2)
print('Output of countries with population greater than 1000000')

nan
Austria            8054800
Belgium           10143047
Denmark            5251027
Finland            5116800
France            58265400
Germany           81845000
Ireland            3591200
Italy             57268578
Netherland        15492800
Norway             4370000
Portugal           9920800
Spain             39241900
Sweden             8837000
Switzerland        7060400
United Kingdom    58684000
Name: 01.01.95, dtype: int64
Output of countries with population greater than 1000000


In [ ]:
# 3. Print the average population in the United Kingdom over those seven years
