In [19]:
# GROUP 3

import numpy as np

st1 = [ 1,2,3,4,5,6,7,8,9]
st2 = ( 1,2,3,4,5,6)
st3 = ( 1,2,3)

x = lambda a: np.mean(a)
print('example 1: {:.2f}'.format(x(st1)))
print('example 2: {:.2f}'.format(x(st2)))
print('example 3: {:.2f}'.format(x(st3)))

example 1: 5.00
example 2: 3.50
example 3: 2.00


Use the Week4-NumpyActivities program, review the snipets of code and then do
the following:

1. Write a Python program to convert a list and tuple into Numpy arrays.

List to array: [1 2 3 4 5 6 7 8] 
Tuple to array:
[[8 4 6]  [1 2 3]]

Discuss how the list and tuple differ from the arrays.

2. Write a Python program to append values to the end of a Numpy array. 

Expected Output:
Original array:
 [10, 20, 30] 
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]
NUMPY Arrays


In [34]:
import numpy as np

toople = (1, 2, 3, 4, 5, 6, 7, 8)
ary = np.array(toople)
type(ary)

toople2 = ([8, 4, 6],  [1, 2, 3])
ary2 = np.array(toople2)
ary2

# 

array([[8, 4, 6],
       [1, 2, 3]])

In [33]:
a = np.array([10,20,30])
b = np.array([1,2,3,4])
print(np.append(a,b))

[10 20 30  1  2  3  4]
